AllCops:
  TargetRubyVersion: 2.3

MethodLength:
  Max: 200

LineLength:
  Max: 175

AbcSize:
  Max: 175

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# syntax is non obvious to a non ruby developer
Style/SafeNavigation:
  Enabled: false
